# -*- coding: utf-8 -*-
# Generated by Django 1.10.8post1 on 2018-06-18 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('cms', '0018_pagenode'),
        ('global_cms_link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsContainerPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='global_cms_contact_us_contactuscontainerpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('bg_image', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.PROTECT, to='filer.File', verbose_name='background image')),
            ],
            options={
                'verbose_name_plural': 'Contact Us Containers',
                'verbose_name': 'Contact Us Container',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContactUsItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=33)),
                ('sub_title', models.CharField(max_length=35)),
                ('phone', models.CharField(max_length=18)),
                ('time', models.CharField(max_length=40)),
                ('cta_text', models.CharField(blank=True, max_length=20, verbose_name='link text')),
                ('cta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='global_cms_link.FilLink', verbose_name='link')),
                ('parent_plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_us_items', to='global_cms_contact_us.ContactUsContainerPluginModel')),
            ],
            options={
                'verbose_name_plural': 'Contact Us Items',
                'verbose_name': 'Contact Us Item',
            },
        ),
    ]
