# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-15 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('global_cms_contact_us', '0002_auto_20190315_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuscontainerpluginmodel',
            name='bg_image',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='filer.File', verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='contactusitemmodel',
            name='cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='global_cms_link.FilLink', verbose_name='link'),
        ),
    ]
