# -*- coding: utf-8 -*-
# Generated by Django 1.10.8post1 on 2018-08-01 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_cms_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillink',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Display name'),
        ),
    ]
